# Generated by Django 5.2.5 on 2025-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userrole_phone_alter_userrole_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('semit', 'Semit'), ('tuludimtu', 'Tulu Dimtu'), ('koye-feche', 'Koye-Feche'), ('arabsa', 'Arabsa'), ('bulbula', 'Bulbula'), ('abado', 'Abado')], max_length=100),
        ),
    ]
