# Generated by Django 5.2.5 on 2025-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('semit', 'Semit'), ('tuludimtu', 'Tulu Dimtu'), ('koye-feche', 'Koye-Feche'), ('arabsa', 'Arabsa'), ('bulbula', 'Bulbula'), ('abado', 'Abado'), ('bole', 'Bole')], max_length=100),
        ),
    ]
