# Generated by Django 5.2.5 on 2025-12-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='property',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
