# Generated by Django 5.2.5 on 2025-12-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_is_verified_property_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
