# Generated by Django 5.2.5 on 2025-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='auto_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
