# Generated by Django 5.2.5 on 2025-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_auto_delete_at_property_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Available From'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_backup_generator',
            field=models.BooleanField(default=False, verbose_name='Has Generator'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='Internet Ready'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
