# Generated by Django 5.2.5 on 2025-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_available_from_property_featured_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_resubmit',
            field=models.BooleanField(default=False),
        ),
    ]
