# Generated by Django 5.2.5 on 2025-12-12 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_conversation_options_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', '💬 New Message'), ('verification', '✅ Property Verified'), ('rejection', '❌ Property Rejected'), ('property_view', '👀 Property Viewed'), ('property_saved', '❤️ Property Saved'), ('property_inquiry', '❓ New Inquiry'), ('property_submission', '📝 New Property Submitted'), ('property_resubmission', '🔄 Property Resubmitted'), ('new_user', '👤 New User Registered'), ('profile_update', '👤 Profile Updated'), ('account_alert', '⚠️ Account Alert'), ('welcome', '👋 Welcome to YebetKiray'), ('tip', '💡 Pro Tip')], max_length=50),
        ),
    ]
