# Generated by Django 5.2.5 on 2025-12-15 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_propertyreview_rating'),
        ('properties', '0004_property_auto_delete_at_property_is_rejected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('property', 'reviewer', 'parent_review')},
        ),
    ]
