# Generated by Django 5.2.5 on 2025-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_propertyreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', '💬 New Message'), ('verification', '✅ Property Verified'), ('rejection', '❌ Property Rejected'), ('property_view', '👀 Property Viewed'), ('property_saved', '❤️ Property Saved'), ('property_inquiry', '❓ New Inquiry'), ('property_review', '⭐ Property Review/Question'), ('review_reply', '👑 Review Reply'), ('featured_upgrade', '🌟 Property Upgraded to Featured'), ('featured_expiring', '⚠️ Featured Status Expiring Soon'), ('featured_expired', '📉 Featured Status Expired'), ('featured_renewed', '✅ Featured Status Renewed'), ('payment_failed', '❌ Featured Payment Failed'), ('property_submission', '📝 New Property Submitted'), ('property_resubmission', '🔄 Property Resubmitted'), ('new_user', '👤 New User Registered'), ('profile_update', '👤 Profile Updated'), ('account_alert', '⚠️ Account Alert'), ('welcome', '👋 Welcome to YebetKiray'), ('tip', '💡 Pro Tip')], max_length=50),
        ),
    ]
